workflows:
  android-build:
    name: StudyMate Android Build
    max_build_duration: 60

    environment:
      android_signing:
        - studymate_keystore

      vars:
        PACKAGE_NAME: "com.praisefxtech.studymate"

    scripts:
      - name: Build Android APK
        script: |
          chmod +x ./gradlew
          ./gradlew assembleRelease

    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab

    publishing:
      email:
        recipients:
          praisekenechukwuchigbo@gmail.com
